version: '{build}'
branches:
  only:
    - master
    - /^release/
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
build_script:
  - ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: UuET4Qm6OHFtzDilCUsagXtDXYS4b2XScRmdrW8eOE3dnCZVNcvq4UA9hXE8EvaU
    skip_symbols: true
    on:
      branch: /^(master|release)/
  - provider: GitHub
    auth_token:
      secure: KklZfNm3JOaDphii0wPCgeRpRmOQEnVmOm+XK4ktEeZe8LFvmDwQadDRfGaalRbf
    artifact: /Serilog.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: /^release/